# Sample OpenTelemetry Collector configuration with semconv processor
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  
  # Prometheus receiver to scrape collector's own metrics
  prometheus:
    config:
      scrape_configs:
        - job_name: 'otelcol-internal'
          scrape_interval: 10s
          static_configs:
            - targets: ['localhost:8888']
              labels:
                service: 'otelcol-semconv'

processors:
  # Batch processor for better performance
  batch:
    timeout: 1s
    send_batch_size: 1024
  
  # Resource processor to enrich collector internal metrics
  resource/collector-telemetry:
    attributes:
      - key: collector.name
        value: "otelcol-semconv"
        action: insert
      - key: collector.version
        value: "0.130.0"
        action: insert
      - key: telemetry.source
        value: "internal"
        action: insert

  # Semantic convention processor for cardinality reduction
  semconv:
    enabled: true
    benchmark: true  # Enable cardinality tracking metrics
    span_processing:
      enabled: true
      mode: "enforce"  # Use "enrich" to only add attributes without changing span names
      preserve_original_name: true
      operation_name_attribute: "operation.name"
      operation_type_attribute: "operation.type"
      original_name_attribute: "name.original"
      rules:
        # HTTP server spans - route normalization (supports both old and new conventions)
        - id: "http_server_routes"
          priority: 100
          span_kind: ["server"]
          condition: 'FirstNonNil([attributes["http.request.method"], attributes["http.method"]]) != nil and attributes["http.route"] != nil'
          operation_name: 'Concat([FirstNonNil([attributes["http.request.method"], attributes["http.method"]]), attributes["http.route"]], " ")'
          operation_type: '"http"'

        # HTTP server spans - method only (supports both old and new conventions)
        - id: "http_server_method_only"
          priority: 110
          span_kind: ["server"]
          condition: 'FirstNonNil([attributes["http.request.method"], attributes["http.method"]]) != nil and attributes["http.route"] == nil'
          operation_name: 'Concat(["HTTP", FirstNonNil([attributes["http.request.method"], attributes["http.method"]])], " ")'
          operation_type: '"http"'

        # HTTP client spans - with url.template (supports both old and new conventions)
        - id: "http_client_template"
          priority: 140
          span_kind: ["client"]
          condition: 'FirstNonNil([attributes["http.request.method"], attributes["http.method"]]) != nil and attributes["url.template"] != nil'
          operation_name: 'Concat([FirstNonNil([attributes["http.request.method"], attributes["http.method"]]), attributes["url.template"]], " ")'
          operation_type: '"http_client"'

        # HTTP client spans - method only (supports both old and new conventions)
        - id: "http_client_method_only"
          priority: 145
          span_kind: ["client"]
          condition: 'FirstNonNil([attributes["http.request.method"], attributes["http.method"]]) != nil and attributes["url.template"] == nil'
          operation_name: 'Concat(["HTTP", FirstNonNil([attributes["http.request.method"], attributes["http.method"]])], " ")'
          operation_type: '"http_client"'

        # HTTP client spans - URL normalization (supports both old and new conventions)
        - id: "http_client_requests"
          priority: 150
          span_kind: ["client"]
          condition: 'FirstNonNil([attributes["http.request.method"], attributes["http.method"]]) != nil and attributes["http.url"] != nil'
          operation_name: 'Concat([FirstNonNil([attributes["http.request.method"], attributes["http.method"]]), RemoveQueryParams(attributes["http.url"])], " ")'
          operation_type: '"http_client"'

        # HTTP path normalization (supports both old and new conventions)
        - id: "http_paths"
          priority: 200
          condition: 'FirstNonNil([attributes["http.request.method"], attributes["http.method"]]) != nil and attributes["url.path"] != nil'
          operation_name: 'Concat([FirstNonNil([attributes["http.request.method"], attributes["http.method"]]), NormalizePath(attributes["url.path"])], " ")'
          operation_type: '"http"'

        # Database client operations
        - id: "database_queries"
          priority: 300
          span_kind: ["client"]  # Database calls are typically client spans
          condition: 'attributes["db.statement"] != nil'
          operation_name: 'ParseSQL(attributes["db.statement"])'
          operation_type: 'attributes["db.system"]'

        # gRPC server operations
        - id: "grpc_server_operations"
          priority: 400
          span_kind: ["server"]
          condition: 'attributes["rpc.system"] == "grpc" and attributes["rpc.method"] != nil'
          operation_name: 'Concat([attributes["rpc.service"], attributes["rpc.method"]], "/")'
          operation_type: '"grpc"'

        # gRPC client operations
        - id: "grpc_client_operations"
          priority: 450
          span_kind: ["client"]
          condition: 'attributes["rpc.system"] == "grpc" and attributes["rpc.method"] != nil'
          operation_name: 'Concat(["grpc.client", attributes["rpc.service"], attributes["rpc.method"]], "/")'
          operation_type: '"grpc_client"'

        # Messaging producer operations
        - id: "messaging_producer"
          priority: 500
          span_kind: ["producer"]
          condition: 'attributes["messaging.operation"] == "publish" and attributes["messaging.destination.name"] != nil'
          operation_name: 'Concat(["publish", attributes["messaging.destination.name"]], " ")'
          operation_type: '"messaging"'

        # Messaging consumer operations
        - id: "messaging_consumer"
          priority: 550
          span_kind: ["consumer"]
          condition: 'attributes["messaging.operation"] == "process" and attributes["messaging.destination.name"] != nil'
          operation_name: 'Concat(["process", attributes["messaging.destination.name"]], " ")'
          operation_type: '"messaging"'

        # Internal operations
        - id: "internal_operations"
          priority: 600
          span_kind: ["internal"]
          condition: 'attributes["internal.operation"] != nil'
          operation_name: 'attributes["internal.operation"]'
          operation_type: '"internal"'

exporters:
  # Debug exporter for testing
  debug:
    verbosity: basic
    sampling_initial: 10
    sampling_thereafter: 100

  # OTLP exporter to Jaeger
  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true

  # Prometheus metrics
  prometheus:
    endpoint: 0.0.0.0:8888

extensions:
  health_check:
    endpoint: 0.0.0.0:13133
  zpages:
    endpoint: 0.0.0.0:55679

service:
  extensions: [health_check, zpages]

  pipelines:
    traces:
      receivers: [otlp]
      processors: [semconv, batch]
      exporters: [debug, otlp/jaeger]

    metrics:
      receivers: [otlp, prometheus]
      processors: [resource/collector-telemetry, batch]
      exporters: [prometheus]

    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]

  telemetry:
    logs:
      level: info
    metrics:
      level: detailed
      address: 0.0.0.0:8888
