// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("semconv")
	ScopeName = "github.com/cedricziel/semconvprocessor/processors/semconvprocessor"
)

const (
	MetricsStability = component.StabilityLevelDevelopment
	TracesStability  = component.StabilityLevelDevelopment
	LogsStability    = component.StabilityLevelDevelopment
)
